import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ScrollToTop from "@/components/ScrollUp/ScrollToTop";
import { Toaster, toast } from 'sonner';
import LoginContext from "@/provider/LoginContext";
import UserProvider from "@/provider/UserContext";
import CartProvider from "@/provider/CartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LoginContext>
          <UserProvider>
          <CartProvider>
          <Toaster/>
          {children}
          <ScrollToTop/>
          </CartProvider>
          </UserProvider>
        </LoginContext>
        
      </body>
    </html>
  );
}
